spring.application.name=gafana-test-service
server.port=${PORT:8080}

management.endpoints.web.exposure.include=health,info,metrics,prometheus

spring.security.user.name=grafana
spring.security.user.password=${GRAFANA_PASSWORD}